const gen1Pokemon = [
    {
      number: 1,
      name: "Bulbasaur",
      typing: ["Grass", "Poison"],
      isMonotype: false,
      isFirstStage: true,
      isSecondStage: false,
      isThirdStage: false,
      isLegendaryOrMythical: false,
      evolvesWithItem: false,
      evolvesByLevelUp: true,
      canMegaEvolve: false,
      canLearnTackle: true,
    },
    {
      number: 2,
      name: "Ivysaur",
      typing: ["Grass", "Poison"],
      isMonotype: false,
      isFirstStage: false,
      isSecondStage: true,
      isThirdStage: false,
      isLegendaryOrMythical: false,
      evolvesWithItem: false,
      evolvesByLevelUp: true,
      canMegaEvolve: false,
      canLearnTackle: true
    },
    {
      number: 3,
      name: "Venusaur",
      typing: ["Grass", "Poison"],
      isMonotype: false,
      isFirstStage: false,
      isSecondStage: false,
      isThirdStage: true,
      isLegendaryOrMythical: false,
      evolvesWithItem: false,
      evolvesByLevelUp: true,
      canMegaEvolve: true,
      canLearnTackle: true
    },
    {
      number: 4,
      name: "Charmander",
      typing: ["Fire"],
      isMonotype: true,
      isFirstStage: true,
      isSecondStage: false,
      isThirdStage: false,
      isLegendaryOrMythical: false,
      evolvesWithItem: false,
      evolvesByLevelUp: true,
      canMegaEvolve: false,
      canLearnTackle: true
    },
    {
      number: 5,
      name: "Charmeleon",
      typing: ["Fire"],
      isMonotype: true,
      isFirstStage: false,
      isSecondStage: true,
      isThirdStage: false,
      isLegendaryOrMythical: false,
      evolvesWithItem: false,
      evolvesByLevelUp: true,
      canMegaEvolve: false,
      canLearnTackle: true
    },
    {
      number: 6,
      name: "Charizard",
      typing: ["Fire", "Flying"],
      isMonotype: false,
      isFirstStage: false,
      isSecondStage: false,
      isThirdStage: true,
      isLegendaryOrMythical: false,
      evolvesWithItem: false,
      evolvesByLevelUp: true,
      canMegaEvolve: true,
      canLearnTackle: true
    },
    {
      number: 7,
      name: "Squirtle",
      typing: ["Water"],
      isMonotype: true,
      isFirstStage: true,
      isSecondStage: false,
      isThirdStage: false,
      isLegendaryOrMythical: false,
      evolvesWithItem: false,
      evolvesByLevelUp: true,
      canMegaEvolve: false,
      canLearnTackle: true
    },
    {
      number: 8,
      name: "Wartortle",
      typing: ["Water"],
      isMonotype: true,
      isFirstStage: false,
      isSecondStage: true,
      isThirdStage: false,
      isLegendaryOrMythical: false,
      evolvesWithItem: false,
      evolvesByLevelUp: true,
      canMegaEvolve: false,
      canLearnTackle: true
    },
    {
      number: 9,
      name: "Blastoise",
      typing: ["Water"],
      isMonotype: true,
      isFirstStage: false,
      isSecondStage: false,
      isThirdStage: true,
      isLegendaryOrMythical: false,
      evolvesWithItem: false,
      evolvesByLevelUp: true,
      canMegaEvolve: true,
      canLearnTackle: true
    },
    {
      number: 10,
      name: "Caterpie",
      typing: ["Bug"],
      isMonotype: true,
      isFirstStage: true,
      isSecondStage: false,
      isThirdStage: false,
      isLegendaryOrMythical: false,
      evolvesWithItem: false,
      evolvesByLevelUp: true,
      canMegaEvolve: false,
      canLearnTackle: true
    },
    {
        number: 11,
        name: "Metapod",
        typing: ["Bug"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 12,
        name: "Butterfree",
        typing: ["Bug", "Flying"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 13,
        name: "Weedle",
        typing: ["Bug", "Poison"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 14,
        name: "Kakuna",
        typing: ["Bug", "Poison"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 15,
        name: "Beedrill",
        typing: ["Bug", "Poison"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: false
      },
      {
        number: 16,
        name: "Pidgey",
        typing: ["Normal", "Flying"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 17,
        name: "Pidgeotto",
        typing: ["Normal", "Flying"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 18,
        name: "Pidgeot",
        typing: ["Normal", "Flying"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 19,
        name: "Rattata",
        typing: ["Normal"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 20,
        name: "Raticate",
        typing: ["Normal"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 21,
        name: "Spearow",
        typing: ["Normal", "Flying"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 22,
        name: "Fearow",
        typing: ["Normal", "Flying"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 23,
        name: "Ekans",
        typing: ["Poison"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 24,
        name: "Arbok",
        typing: ["Poison"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 25,
        name: "Pikachu",
        typing: ["Electric"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 26,
        name: "Raichu",
        typing: ["Electric"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 27,
        name: "Sandshrew",
        typing: ["Ground"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 28,
        name: "Sandslash",
        typing: ["Ground"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 29,
        name: "Nidoran♀",
        typing: ["Poison"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 30,
        name: "Nidorina",
        typing: ["Poison"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 31,
        name: "Nidoqueen",
        typing: ["Poison", "Ground"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 32,
        name: "Nidoran♂",
        typing: ["Poison"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 33,
        name: "Nidorino",
        typing: ["Poison"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 34,
        name: "Nidoking",
        typing: ["Poison", "Ground"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 35,
        name: "Clefairy",
        typing: ["Fairy"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 36,
        name: "Clefable",
        typing: ["Fairy"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 37,
        name: "Vulpix",
        typing: ["Fire"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 38,
        name: "Ninetales",
        typing: ["Fire"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 39,
        name: "Jigglypuff",
        typing: ["Normal", "Fairy"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 40,
        name: "Wigglytuff",
        typing: ["Normal", "Fairy"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 41,
        name: "Zubat",
        typing: ["Poison", "Flying"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 42,
        name: "Golbat",
        typing: ["Poison", "Flying"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 43,
        name: "Oddish",
        typing: ["Grass", "Poison"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 44,
        name: "Gloom",
        typing: ["Grass", "Poison"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 45,
        name: "Vileplume",
        typing: ["Grass", "Poison"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 46,
        name: "Paras",
        typing: ["Bug", "Grass"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 47,
        name: "Parasect",
        typing: ["Bug", "Grass"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 48,
        name: "Venonat",
        typing: ["Bug", "Poison"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 49,
        name: "Venomoth",
        typing: ["Bug", "Poison"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 50,
        name: "Diglett",
        typing: ["Ground"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 51,
        name: "Dugtrio",
        typing: ["Ground"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 52,
        name: "Meowth",
        typing: ["Normal"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 53,
        name: "Persian",
        typing: ["Normal"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 54,
        name: "Psyduck",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 55,
        name: "Golduck",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 56,
        name: "Mankey",
        typing: ["Fighting"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 57,
        name: "Primeape",
        typing: ["Fighting"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 58,
        name: "Growlithe",
        typing: ["Fire"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 59,
        name: "Arcanine",
        typing: ["Fire"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 60,
        name: "Poliwag",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 61,
        name: "Poliwhirl",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 62,
        name: "Poliwrath",
        typing: ["Water", "Fighting"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 63,
        name: "Abra",
        typing: ["Psychic"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 64,
        name: "Kadabra",
        typing: ["Psychic"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 65,
        name: "Alakazam",
        typing: ["Psychic"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: false
      },
      {
        number: 66,
        name: "Machop",
        typing: ["Fighting"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 67,
        name: "Machoke",
        typing: ["Fighting"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 68,
        name: "Machamp",
        typing: ["Fighting"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 69,
        name: "Bellsprout",
        typing: ["Grass", "Poison"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 70,
        name: "Weepinbell",
        typing: ["Grass", "Poison"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 71,
        name: "Victreebel",
        typing: ["Grass", "Poison"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: false
      },
      {
        number: 72,
        name: "Tentacool",
        typing: ["Water", "Poison"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 73,
        name: "Tentacruel",
        typing: ["Water", "Poison"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 74,
        name: "Geodude",
        typing: ["Rock", "Ground"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 75,
        name: "Graveler",
        typing: ["Rock", "Ground"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 76,
        name: "Golem",
        typing: ["Rock", "Ground"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 77,
        name: "Ponyta",
        typing: ["Fire"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 78,
        name: "Rapidash",
        typing: ["Fire"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 79,
        name: "Slowpoke",
        typing: ["Water", "Psychic"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 80,
        name: "Slowbro",
        typing: ["Water", "Psychic"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 81,
        name: "Magnemite",
        typing: ["Electric", "Steel"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 82,
        name: "Magneton",
        typing: ["Electric", "Steel"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 83,
        name: "Farfetch'd",
        typing: ["Normal", "Flying"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 84,
        name: "Doduo",
        typing: ["Normal", "Flying"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 85,
        name: "Dodrio",
        typing: ["Normal", "Flying"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 86,
        name: "Seel",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 87,
        name: "Dewgong",
        typing: ["Water", "Ice"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 88,
        name: "Grimer",
        typing: ["Poison"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 89,
        name: "Muk",
        typing: ["Poison"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 90,
        name: "Shellder",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 91,
        name: "Cloyster",
        typing: ["Water", "Ice"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 92,
        name: "Gastly",
        typing: ["Ghost", "Poison"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 93,
        name: "Haunter",
        typing: ["Ghost", "Poison"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 94,
        name: "Gengar",
        typing: ["Ghost", "Poison"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 95,
        name: "Onix",
        typing: ["Rock", "Ground"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 96,
        name: "Drowzee",
        typing: ["Psychic"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 97,
        name: "Hypno",
        typing: ["Psychic"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 98,
        name: "Krabby",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 99,
        name: "Kingler",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 100,
        name: "Voltorb",
        typing: ["Electric"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 101,
        name: "Electrode",
        typing: ["Electric"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 102,
        name: "Exeggcute",
        typing: ["Grass", "Psychic"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 103,
        name: "Exeggutor",
        typing: ["Grass", "Psychic"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 104,
        name: "Cubone",
        typing: ["Ground"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 105,
        name: "Marowak",
        typing: ["Ground"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 106,
        name: "Hitmonlee",
        typing: ["Fighting"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 107,
        name: "Hitmonchan",
        typing: ["Fighting"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 108,
        name: "Lickitung",
        typing: ["Normal"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 109,
        name: "Koffing",
        typing: ["Poison"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 110,
        name: "Weezing",
        typing: ["Poison"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 111,
        name: "Rhyhorn",
        typing: ["Rock", "Ground"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 112,
        name: "Rhydon",
        typing: ["Rock", "Ground"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 113,
        name: "Chansey",
        typing: ["Normal"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 114,
        name: "Tangela",
        typing: ["Grass"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 115,
        name: "Kangaskhan",
        typing: ["Normal"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 116,
        name: "Horsea",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 117,
        name: "Seadra",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 118,
        name: "Goldeen",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 119,
        name: "Seaking",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 120,
        name: "Staryu",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 121,
        name: "Starmie",
        typing: ["Water", "Psychic"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 122,
        name: "Mr. Mime",
        typing: ["Psychic", "Fairy"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 123,
        name: "Scyther",
        typing: ["Bug", "Flying"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 124,
        name: "Jynx",
        typing: ["Ice", "Psychic"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 125,
        name: "Electabuzz",
        typing: ["Electric"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 126,
        name: "Magmar",
        typing: ["Fire"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 127,
        name: "Pinsir",
        typing: ["Bug"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 128,
        name: "Tauros",
        typing: ["Normal"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 129,
        name: "Magikarp",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 130,
        name: "Gyarados",
        typing: ["Water", "Flying"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 131,
        name: "Lapras",
        typing: ["Water", "Ice"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 132,
        name: "Ditto",
        typing: ["Normal"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 133,
        name: "Eevee",
        typing: ["Normal"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 134,
        name: "Vaporeon",
        typing: ["Water"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 135,
        name: "Jolteon",
        typing: ["Electric"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 136,
        name: "Flareon",
        typing: ["Fire"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 137,
        name: "Porygon",
        typing: ["Normal"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: true,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 138,
        name: "Omanyte",
        typing: ["Rock", "Water"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 139,
        name: "Omastar",
        typing: ["Rock", "Water"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 140,
        name: "Kabuto",
        typing: ["Rock", "Water"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 141,
        name: "Kabutops",
        typing: ["Rock", "Water"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 142,
        name: "Aerodactyl",
        typing: ["Rock", "Flying"],
        isMonotype: false,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 143,
        name: "Snorlax",
        typing: ["Normal"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 144,
        name: "Articuno",
        typing: ["Ice", "Flying"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: true,
        evolvesWithItem: false,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 145,
        name: "Zapdos",
        typing: ["Electric", "Flying"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: true,
        evolvesWithItem: false,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 146,
        name: "Moltres",
        typing: ["Fire", "Flying"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: true,
        evolvesWithItem: false,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 147,
        name: "Dratini",
        typing: ["Dragon"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 148,
        name: "Dragonair",
        typing: ["Dragon"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: true,
        isThirdStage: false,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: false,
        canLearnTackle: true
      },
      {
        number: 149,
        name: "Dragonite",
        typing: ["Dragon", "Flying"],
        isMonotype: false,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: true,
        isLegendaryOrMythical: false,
        evolvesWithItem: false,
        evolvesByLevelUp: true,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 150,
        name: "Mewtwo",
        typing: ["Psychic"],
        isMonotype: true,
        isFirstStage: false,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: true,
        evolvesWithItem: false,
        evolvesByLevelUp: false,
        canMegaEvolve: true,
        canLearnTackle: true
      },
      {
        number: 151,
        name: "Mew",
        typing: ["Psychic"],
        isMonotype: true,
        isFirstStage: true,
        isSecondStage: false,
        isThirdStage: false,
        isLegendaryOrMythical: true,
        evolvesWithItem: false,
        evolvesByLevelUp: false,
        canMegaEvolve: false,
        canLearnTackle: true
      },
            ];
  